export default {
    stt: '搜索',
    tindex: '1',
    countsindex: '/count/countachieve',
    marketingsindex: '/marketing/manjian',
    membersindex: '/member/membermanager',
    ordersindex: '/order/orderlist',
    settingsindex: '/setting/search',
    shoppingsindex: '/shopping/shoppinglist',
    usersindex: '/user/userlist',
    user: {},
    token: null,
    title: '',
    toLogin: false,
    fullscreenLoadings: true,
    fullscreenLoadings1: true,
    fullscreenLoadings2: true,
    fullscreenLoadings3: true,
    fullscreenLoadings4: true,
    fullscreenLoadings5: true,
    fullscreenLoadings6: true,
    order_sn: '',
    bstop: true
}